---
title: "Data aggregation, cleaning, and EDA"
date: "April 14th 2020"
output: html_notebook
---

```{r setup, include=FALSE}
library(fs) #file utils
library(lubridate) # date utils 
library(DT) # pretty interactive data tables
library(tidyverse)
```

## Datasets used: 

(Obviously can be adjusted)

Arizona: 
- PM 2.5 data for 2020 
- Carbon Monoxide data for 2020
- Covid cases by county

California:
- PM 2.5 data for 2020 
- Carbon Monoxide data for 2020
- Covid cases by county

### Initial import & cleaning (Note that many locations lack PM 2.5 *and* CO data): 

```{r datasets}
data_directory <- "/Users/oana/Documents/github/duke_datafest_covid19/datasets" # change appropriately

# Covid data from NYT: https://github.com/nytimes/covid-19-data 
covid_by_county_url <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
covid_by_county_dfs <- read_csv(url(covid_by_county_url)) %>% 
  filter(state %in% c("California", "Arizona")) %>% 
  mutate_if(is.character, toupper) %>% 
  rename_all(toupper) %>% 
  group_by(STATE) %>% # split by state to be able to combine w/EPA data more easily 
  group_split()

# Arizona EPA data
az_files <- fs::dir_ls(data_directory, regexp = "ad_viz_plotval_data_AZ*")
az_df <- az_files %>% 
  map(read_csv) %>% 
  map(~ .x %>% 
        mutate_if(is.character, toupper)) %>% 
  reduce(full_join, 
         by=c("Date","STATE_CODE", "STATE", "COUNTY_CODE", "COUNTY", "Site ID", "Site Name", "SITE_LATITUDE", "SITE_LONGITUDE", "CBSA_CODE", "CBSA_NAME"), 
         suffix = c("_co", "_pm25")) %>% 
  rename_all(toupper) %>% 
  mutate_at("DATE", function(x) as.Date(x, format = "%m/%d/%Y")) %>% 
  left_join(covid_by_county_dfs[[1]], by=c("DATE", "STATE", "COUNTY"))

# California EPA data 
ca_files <- fs::dir_ls(data_directory, regexp = "ad_viz_plotval_data_CA*")
ca_df <- ca_files %>% 
  map(read_csv) %>% 
  map(~ .x %>% 
        mutate_if(is.character, toupper)) %>% 
  reduce(full_join, 
         by=c("Date","STATE_CODE", "STATE", "COUNTY_CODE", "COUNTY", "Site ID", "Site Name", "SITE_LATITUDE", "SITE_LONGITUDE", "CBSA_CODE", "CBSA_NAME"), 
         suffix = c("_co", "_pm25")) %>% 
  rename_all(toupper) %>% 
  mutate_at("DATE", function(x) as.Date(x, format = "%m/%d/%Y")) %>% 
  left_join(covid_by_county_dfs[[2]], by=c("DATE", "STATE", "COUNTY"))
```

### Look @ data sets:

```{r}
# A simplified list of columns to look at. I don't know what a lot of them mean so this is just a guess. 
relevant_initial_cols <- c("DATE", "STATE", "COUNTY", "SITE NAME", "DAILY MAX 8-HOUR CO CONCENTRATION", "DAILY MEAN PM2.5 CONCENTRATION", "CASES", "DEATHS")

#Note. According to [this site](covid19.healthdata.org), California's stay at home order was March 19th, 2020. 
ca_stay_at_home_start <- as.Date("2020-03-19")
```

```{r}
az_df %>% 
  select(relevant_initial_cols) %>% 
  filter(DATE > ca_stay_at_home_start) %>% 
  datatable(filter="top", 
            caption="AZ data on CO, PM 2.5, & COVID Cases/Deaths")
```

```{r}
ca_df %>% 
  select(relevant_initial_cols) %>% 
  filter(DATE > ca_stay_at_home_start) %>% 
  datatable(filter="top", 
            caption="CA data on CO, PM 2.5, & COVID Cases/Deaths")
```


## Exploratory Data Analysis (EDA)

```{r}
library(maps)
library(ggmap)
library(mapdata)
library(ggthemes)
library(gganimate)
library(gifski)

az_after_stay_at_home <- az_df %>% 
  filter(DATE > ca_stay_at_home_start) 
  #filter(DATE == "2020-04-15")

az_map <- map_data("county", "arizona")

az_map_plot <- ggplot() + 
  geom_polygon(data=az_map, aes(x=long, y = lat, group = group), fill="lightgrey", color="white") +
  coord_fixed(1.3) + 
  geom_point(data= az_after_stay_at_home, 
             aes(x=SITE_LONGITUDE, y=SITE_LATITUDE, 
                 size=40, 
                 fill=`DAILY MEAN PM2.5 CONCENTRATION`),
             colour="black",
             alpha=0.8,
             pch=21) + 
  #transition_time(DATE) + 
  scale_fill_viridis_b(option="magma", 
                       direction = 1,
                           name = "Natural log of daily mean PM 2.5 Concentration",
    guide = guide_colorbar(
      direction = "horizontal",
      barheight = unit(2, units = "mm"),
      barwidth = unit(50, units = "mm"),
      draw.ulim = F,
      title.position = 'top',
      # some shifting around
      title.hjust = 0.5,
      label.hjust = 0.5
  )) + 
  labs(title="Arizona PM 2.5 levels: {closest_state}") + 
  theme_map() + 
  guides(size=FALSE) + 
  theme(legend.position="bottom") + 
  transition_states(DATE, 
                    transition_length=3,
                    state_length = 20) + 
  view_follow()
animate(az_map_plot, 
        renderer=gifski_renderer(),
        fps=2)
```

```{r}
az_map_ani <- az_map_plot + 
  transition_manual(DATE) 
animate(az_map_ani, renderer=gifski_renderer())
```


